import json

# Read the config file
with open('config.json') as f:
    config = json.load(f)

SUMMARIZE_EMAIL_MODEL = config['MODELS']['SUMMARIZE_EMAIL']
SUMMARIZE_LINKS_MODEL = config['MODELS']['SUMMARIZE_LINKS']
SUMMARIZE_LINKS_BACKUP_MODEL = config['MODELS']['SUMMARIZE_LINKS_BACKUP']
CONSOLIDATE_TITLES_MODEL = config['MODELS']['CONSOLIDATE_TITLES']
SUMMARIZE_SUMMARIES_MODEL = config['MODELS']['SUMMARIZE_SUMMARIES']
EMBEDDINGS_MODEL = config['MODELS']['EMBEDDINGS']
MODEL_CONFIGS = config['MODEL_CONFIGS']

EMAIL_LIST = config['EMAIL_LIST']
URLS_TO_IGNORE = config['URLS_TO_IGNORE']
PATHS_TO_IGNORE = config['PATHS_TO_IGNORE']
UNSUBSCRIBE_KEYWORDS = config['UNSUBSCRIBE_KEYWORDS']
LINKS_CLASSES_TO_IGNORE = config['LINKS_CLASSES_TO_IGNORE']
LINK_TEXT_TO_IGNORE = config['LINK_TEXT_TO_IGNORE']